name = "SafeIO"
uuid = "b60d60a1-a286-437d-88e3-564ee59fee65"
version = "0.5.2"
authors = ["Waylon Wu <waylon_wu@outlook.com>"]

[deps]
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CRC32c = "1.10.10"
Dates = "1.10.10"
JLD2 = "0.6.3"
Logging = "1.10.10"
Test = "1.10.10"
TimeZones = "1.22.2"
UUIDs = "1.10.10"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Logging", "Test"]
